"use client";

import { Check, FileText, Layers3 } from "lucide-react";

const options = [{ value: 1, label: "Full page", detail: "Maximum writing room" }, { value: 2, label: "2-up", detail: "A balanced study sheet" }, { value: 3, label: "3-up", detail: "Compact and economical" }, { value: 4, label: "4-up", detail: "Maximum ink savings" }];

export default function SidebarSettings({ nUp, setNUp, format, setFormat }) {
  return <aside className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 text-[var(--text-main)] soft-shadow"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--mint)] text-[var(--accent-mint)]"><Layers3 size={16} /></span><div><p className="text-sm font-bold text-[var(--text-main)]">Sheet layout</p><p className="text-xs text-[var(--text-muted)]">Stacked vertically on A4</p></div></div><div className="mt-5 space-y-2">{options.map((option) => <button key={option.value} onClick={() => setNUp(option.value)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left transition ${nUp === option.value ? "border-[var(--accent-mint)] bg-[var(--bg-secondary)]" : "border-[var(--border-color)] bg-[var(--bg-card)] hover:border-[var(--accent-mint)]"}`}><span><span className="block text-sm font-bold text-[var(--text-main)]">{option.label}</span><span className="text-xs text-[var(--text-muted)]">{option.detail}</span></span><span className={`grid h-6 w-6 place-items-center rounded-full border ${nUp === option.value ? "border-[var(--accent-mint)] bg-[var(--accent-mint)] text-[var(--bg-main)]" : "border-[var(--border-color)] text-transparent"}`}>{nUp === option.value && <Check size={13} />}</span></button>)}</div><div className="mt-6 border-t border-[var(--border-color)] pt-5"><div className="flex items-center gap-2"><FileText size={15} className="text-[var(--accent-coral)]" /><p className="text-sm font-bold">Export format</p></div><div className="mt-3 flex rounded-xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-1"><button onClick={() => setFormat("pdf")} className={`flex flex-1 items-center justify-center rounded-lg px-3 py-2 text-xs font-bold ${format === "pdf" ? "bg-[var(--bg-card)] text-[var(--text-main)] shadow-sm" : "text-[var(--text-muted)]"}`}>PDF</button><button onClick={() => setFormat("docx")} className={`flex flex-1 items-center justify-center rounded-lg px-3 py-2 text-xs font-bold ${format === "docx" ? "bg-[var(--bg-card)] text-[var(--text-main)] shadow-sm" : "text-[var(--text-muted)]"}`}>DOCX</button></div></div></aside>;
}
